[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["Ishaan Gupta <a-ishaagupta@expediagroup.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
