name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd project
          poetry install
      - name: Run tests
        run: |
          cd project/source
          poetry run python data_gen.py
          poetry run python compute_aggregates.py
          poetry run python -m unittest unit_tests/unit_tests.py
          poetry run python truncate_table.py

